Init nftables, normaly done in sunet::server
When 'sshd_config: false' is set, nftables is not initiated.
So we get this error:
Error: Could not find resource 'Service[nftables]' in parameter 'notify' (file: /etc/puppet/cosmos-modules/sunet/manifests/dockerhost2.pp, line: 40)