Change nftables fw opening syntax.
Since the alloy client is not docker based we can use the
sunet::nftables::allow syntax instead. Otherwise we get this error on
modern servers not running docker:

Error: Evaluation Error: Error while evaluating a Resource Statement,
Evaluation Error: Unknown function: 'has_key'. (file:
/etc/puppet/cosmos-modules/sunet/manifests/nftables/docker_expose.pp,
line: 36, column: 10) (file:
/etc/puppet/cosmos-modules/sunet/manifests/otel/alloy.pp, line: 50) on
node X