dockerhost2: include apt
This is expected by the module, and not doing so either causes warnings
on puppet 7:
```
Warning: Unknown variable: 'apt::key_options'. (file: /usr/share/puppet/modules/apt/manifests/key.pp, line: 45, column: 123)
```
... or stops the run entirely on puppet 8:
```
Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Unknown variable: 'apt::key_options'. (file: /usr/share/puppet/modules/apt/manifests/key.pp, line: 45, column: 123) (file: /etc/puppet/cosmos-modules/sunet/manifests/dockerhost2.pp, line: 71) on node somehost-1.sunet.se
```