Use the moderna alternative for ubuntu 26.
We got these errors:
Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: W: OpenPGP signature verification failed: https://download.docker.com/linux/ubuntu resolute InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: E: The repository 'https://download.docker.com/linux/ubuntu resolute InRelease' is not signed.
Error: /Stage[main]/Apt::Update/Exec[apt_update]: Failed to call refresh: '/usr/bin/apt-get update' returned 100 instead of one of [0]
Error: /Stage[main]/Apt::Update/Exec[apt_update]: '/usr/bin/apt-get update' returned 100 instead of one of [0]
Notice: /Stage[main]/Sunet::Dockerhost2/Apt::Key[docker_ce]/Anchor[apt_key 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 present]: Dependency Apt_key[docker_ce] has failures: true
Warning: /Stage[main]/Sunet::Dockerhost2/Apt::Key[docker_ce]/Anchor[apt_key 9DC858229FC7DD38854AE2D88D81803C0EBFCD88 present]: Skipping because of failed dependencies