knubbis: remove global require for nagios
Try to break dependency chain:
```
Error: Found 1 dependency cycle:
(Exec[concat_/etc/nagios/nrpe.d/sunet_nrpe_commands.cfg] => Concat[/etc/nagios/nrpe.d/sunet_nrpe_commands.cfg] => Class[Sunet::Nagios::Nrpe] => Class[Sunet::Knubbis::Fleetlock_standalone] => Sunet::Nagios::Nrpe_command[check_knubbis_fl_stale_locks] => Concat::Fragment[sunet_nrpe_command_check_knubbis_fl_stale_locks] => File[/var/lib/puppet/concat/_etc_nagios_nrpe.d_sunet_nrpe_commands.cfg/fragments/30_sunet_nrpe_command_check_knubbis_fl_stale_locks] => Exec[concat_/etc/nagios/nrpe.d/sunet_nrpe_commands.cfg])\nTry the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
Error: Failed to apply catalog: One or more resource dependency cycles detected in graph
```